spring:
  profiles: dev
  application:
    name: csuftspider
#DataSource  Config
#  datasource:
#    url:
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: 86400
# redis Config
  redis:
    port: 6379 #端口号
    password:  #输入redis数据库密码
    host: 127.0.0.1  #输入ip地址

    jedis:
      pool:
        max-idle: 6    #最大空闲数
        max-active: 10 #最大连接数
        min-idle: 2    #最小空闲数
    timeout: 2000   #连接超时

server:
  port: 8082
  servlet:
    context-path: /api


#自定义配置
csuftspider:
#bark for ios
# https://bark.day.app/#/tutorial bark 推送到 IOS
  bark:
      title: CSUFTSPIDER #推送标题
      serverUrl: https://api.day.app #推送 bark url
      apiKey: #apiKey
      level: active #推送显示方式active：默认值，系统会立即亮屏显示通知 timeSensitive：时效性通知，可在专注状态下显示通知。passive：仅将通知添加到通知列表，不会亮屏提醒。
      autoCopy: 1  #是否复制
      group: 开发通知  #分组名称
      icon: #推送图标

# baidu api for ocr
#验证码图像识别 api https://ai.baidu.com/ai-doc/OCR/

  baidu:
      ocr:
        baiduAk:
        baiduSk:

# 系统System Settings
  system:
    #系统登录
    login:
      method: 0 #0 默认开启 登录sm4加密（salt需要配置密钥）,1 不开启加密
      salt:  #SM4加密密钥 16位


#mybatis-plus Config
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#
#  global-config:
#    db-config:
#      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


---
spring:
  profiles: prod
  application:
    name: csuftspider
  #DataSource  Config
#  datasource:
#    url:
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: 86400
#mybatis-plus Config
server:
  port: 8085
  servlet:
    context-path: /api
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#
#  global-config:
#    db-config:
#      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

---


spring:
  profiles.active: dev



